apiVersion: run.tanzu.vmware.com/v1alpha3
kind: TanzuKubernetesCluster
metadata:
  name: v1alpha3-tkc
  namespace: dco-namespace
  annotations:
    run.tanzu.vmware.com/resolve-os-image: os-name=ubuntu
spec:
  topology:
    controlPlane:
      replicas: 1
      vmClass: best-effort-medium
      storageClass: goldsp
      tkr:
        reference:
          name: v1.30.1---vmware.1-fips-tkg.5
    nodePools:
    - replicas: 3
      name: worker
      vmClass: best-effort-medium
      storageClass: goldsp
  settings:
    storage:
      defaultClass: goldsp
    network:
     cni:
       name: antrea-nsx-routed
     services:
       cidrBlocks: ["10.97.0.0/24"]